version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 891377194889.dkr.ecr.us-east-2.amazonaws.com/voting-service:latest .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 891377194889.dkr.ecr.us-east-2.amazonaws.com/voting-service:latest
      - echo Build completed on `date`
